gpu_id: [0]

exp_name: LaRa/release-test
n_views: 4

model:

    encoder_backbone: 'vit_base_patch16_224.dino' # ['vit_small_patch16_224.dino','vit_base_patch16_224.dino']

    n_groups: [16]  # n_groups for local attention
    n_offset_groups: 32     # offset radius of 1/n_offset_groups of the scene size

    K: 2    # primitives per-voxel
    sh_degree: 1    # view dependent color

    num_layers: 12 # 12
    num_heads: 16

    view_embed_dim: 32
    embedding_dim: 256

    vol_feat_reso: 16
    vol_embedding_reso: 32

    vol_embedding_out_dim: 80

    img_feats_avg: True

    padding_size: [864, 1104]

    ckpt_path: null # specify a ckpt path if you want to continue training  

train_dataset:
    dataset_name: custom # housecat6d
    # data_root: dataset/gobjaverse/gobjaverse.h5, /mnt/hdd/lara_data/dataset/Co3D/co3d_teddybear.h5, /home/lu/project/LaRa/housecat_objects_instances, /mnt/hdd/lara_data/dataset/housecat6d
    data_root: /home/lu/project/LaRa/housecat_objects_instances

    split: train
    img_size: [512, 512] # image resolution, [852,1096]
    n_group: ${n_views}
    suv_with_more_views: False
    n_scenes: 240
    load_normal: False

    

test_dataset:
    dataset_name: custom
    # data_root: dataset/gobjaverse/gobjaverse.h5, /mnt/hdd/lara_data/dataset/Co3D/co3d_teddybear.h5, /home/lu/project/LaRa/housecat_objects_instances, /mnt/hdd/lara_data/dataset/housecat6d
    data_root: /home/lu/project/LaRa/housecat_objects_instances

    split: test
    img_size: [512, 512]
    n_group: ${n_views}
    n_scenes: 240
    load_normal: False

train:
    batch_size: 3
    lr: 3e-4
    beta1: 0.9
    beta2: 0.95
    weight_decay: 0.05
    # betas: [0.9, 0.95]
    warmup_iters: 150
    n_epoch: 3000
    limit_train_batches: 1.0 # 0.2
    limit_val_batches: 1.0 # 0.02
    check_val_every_n_epoch: 100
    start_fine: 2000
    use_rand_views: False
test:
    batch_size: 3

logger: 
    name: wandb
    dir: logs/${exp_name}
